name: BanSystem
version: ${project.version}
main: io.github.l1ttle_org.bansystem.BanSystem
api-version: 1.13
authors: [ l1ttle, ItsAlvinThePro ]
description: Ping, pong!
website: https://github.com/l1ttle-org/BanSystem/

commands:
  ban:
    description: Bans a player. Use '_' instead of spaces in <reason>.
    permission: bansystem.ban
    usage: /<command> <player> [-s] <reason>
  unban:
    description: Unbans a player. Use '_' instead of spaces in <reason>.
    permission: bansystem.unban
    usage: /<command> <player> [-s] <reason>
    aliases: [ pardon ]
  kick:
    description: Kicks a player. Use '_' instead of spaces in <reason>.
    permission: bansystem.kick
    usage: /<command> <player> [-s] <reason>
  mute:
    description: Mutes a player. Use '_' instead of spaces in <reason>.
    permission: bansystem.mute
    usage: /<command> <player> [-s] <reason>
  unmute:
    description: Unmutes a player. Use '_' instead of spaces in <reason>.
    permission: bansystem.unmute
    usage: /<command> <player> [-s] <reason>
  blacklist:
    description: Blacklists a player. Use '_' instead of spaces in <reason>.
    permission: bansystem.blacklist
    usage: /<command> <player> [-s] <reason>
permissions:
  bansystem.ban:
    description: Allows execution of /ban command.
  bansystem.blacklist:
    description: Allows execution of /blacklist command.
  bansystem.kick:
    description: Allows execution of /kick command.
  bansystem.mute:
    description: Allows execution of /mute command.
  bansystem.unban:
    description: Allows execution of /unban command.
  bansystem.unblacklist:
    description: Allows execution of /unblacklist command.
  bansystem.unmute:
    description: Allows execution of /unmute command.
  bansystem.notify:
    description: Allows getting notifications.
  bansystem.*:
    description: Grants every permission registered by this plugin.
    default: op
    children:
      bansystem.ban: true
      bansystem.blacklist: true
      bansystem.kick: true
      bansystem.mute: true
      bansystem.unban: true
      bansystem.unblacklist: true
      bansystem.unmute: true
      bansystem.notify: true
