name: BanSystem
version: ${project.version}
main: io.github.l1ttle_org.bansystem.BanSystem
api-version: 1.13
authors: [ l1ttle, ItsAlvinThePro ]
description: Ping, pong!
website: https://github.com/l1ttle-org/BanSystem/

commands:
  ban:
    description: Bans a player. Ban reason is required, use `-s` to ban silently. Duration is optional
    permission: bansystem.ban
    usage: /<command> <player> [-s] <reason>
  unban:
    description: Unbans a player. Always silent
    permission: bansystem.unban
    usage: /<command> <player>

permissions:
  bansystem.ban:
    description: Allows execution of /ban command
  bansystem.unban:
    description: Allows execution of /unban command
  bansystem.notify:
    description: Allows getting notifications
  bansystem.*:
    description: Grants every permission registered by this plugin.
    default: op
    children:
      bansystem.ban: true
      bansystem.unban: true
      bansystem.notify: true
